/*
 * SettlersText.java
 *
 * Created on 5 de enero de 2003, 2:28
 */

package Settlers;

public class SettlersText extends javax.swing.JPanel {
    SettlersGui parent=null;

    /** Creates new form SettlersText */
    public SettlersText(SettlersGui _parent) {
        parent=_parent;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();
        txtInput = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();

        setLayout(null);

        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2));
        txtOutput.setBackground(java.awt.Color.lightGray);
        txtOutput.setEditable(false);
        txtOutput.setForeground(java.awt.Color.darkGray);
        jScrollPane1.setViewportView(txtOutput);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 10, 510, 40);

        txtInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInputKeyTyped(evt);
            }
        });

        add(txtInput);
        txtInput.setBounds(0, 60, 430, 20);

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        add(btnSend);
        btnSend.setBounds(432, 60, 80, 20);

    }//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        write();
    }//GEN-LAST:event_btnSendActionPerformed

    private void txtInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputKeyTyped
        if (evt.getKeyChar()=='\n'){
            write();
        }
    }//GEN-LAST:event_txtInputKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField txtInput;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton btnSend;
    private javax.swing.JTextArea txtOutput;
    // End of variables declaration//GEN-END:variables

    private void write(){
        String str=txtInput.getText();
        write(str);
        txtInput.setText("");        
        parent.getController().write(str);
    }
    
    public void write(String txt){
        txtOutput.append("  "+txt+"\n");
    }
}
