/*
 * SettlersMenu.java
 *
 * Created on 5 de enero de 2003, 23:49
 */

package Settlers;

import java.awt.*;

/**
 *
 * @author  Dodger
 */
public class SettlersMenu extends javax.swing.JPanel {
    private SettlersGui parent;
    /** Creates new form SettlersMenu */
    public SettlersMenu(SettlersGui _parent) {
        initComponents();
        parent=_parent;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        lblResources = new javax.swing.JLabel();
        lblWood = new javax.swing.JLabel();
        lblBricks = new javax.swing.JLabel();
        lblWheat = new javax.swing.JLabel();
        lblSheep = new javax.swing.JLabel();
        lblOre = new javax.swing.JLabel();
        btnTrade = new javax.swing.JButton();
        lblDevelopment = new javax.swing.JLabel();
        lblKnights = new javax.swing.JLabel();
        lblVPD0 = new javax.swing.JLabel();
        lblVPD1 = new javax.swing.JLabel();
        lblVPD2 = new javax.swing.JLabel();
        lblVPD3 = new javax.swing.JLabel();
        lblVPD4 = new javax.swing.JLabel();
        lblVPD5 = new javax.swing.JLabel();
        lblVPD6 = new javax.swing.JLabel();
        btnMonopoly = new javax.swing.JButton();
        btnKnight = new javax.swing.JButton();
        lblCosts = new javax.swing.JLabel();
        lblTitleVP = new javax.swing.JLabel();
        btnRoad = new javax.swing.JButton();
        lblC0 = new javax.swing.JLabel();
        lblC1 = new javax.swing.JLabel();
        btnSettlement = new javax.swing.JButton();
        lblC3 = new javax.swing.JLabel();
        lblC4 = new javax.swing.JLabel();
        lblC5 = new javax.swing.JLabel();
        lblC6 = new javax.swing.JLabel();
        btnCity = new javax.swing.JButton();
        lblC7 = new javax.swing.JLabel();
        lblC8 = new javax.swing.JLabel();
        lblC9 = new javax.swing.JLabel();
        lblC10 = new javax.swing.JLabel();
        lblC11 = new javax.swing.JLabel();
        btnCard = new javax.swing.JButton();
        lblC12 = new javax.swing.JLabel();
        lblC13 = new javax.swing.JLabel();
        lblC14 = new javax.swing.JLabel();
        lblVP = new javax.swing.JLabel();
        lblPlayers = new javax.swing.JLabel();
        lblJ1 = new javax.swing.JLabel();
        lblJ2 = new javax.swing.JLabel();
        lblJ3 = new javax.swing.JLabel();
        lblJ4 = new javax.swing.JLabel();
        btnRoads = new javax.swing.JButton();
        btnDiscovery = new javax.swing.JButton();

        setLayout(null);

        setPreferredSize(new java.awt.Dimension(100, 600));
        lblResources.setFont(new java.awt.Font("Lucida Bright", 1, 18));
        lblResources.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblResources.setText("Resources");
        add(lblResources);
        lblResources.setBounds(10, 10, 250, 22);

        lblWood.setFont(new java.awt.Font("Dialog", 0, 12));
        lblWood.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Settlers/images/wood2.jpg")));
        lblWood.setText("00");
        lblWood.setToolTipText("Wood");
        add(lblWood);
        lblWood.setBounds(20, 40, 40, 20);

        lblBricks.setFont(new java.awt.Font("Dialog", 0, 12));
        lblBricks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBricks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Settlers/images/bricks2.jpg")));
        lblBricks.setText("00");
        lblBricks.setToolTipText("Bricks");
        add(lblBricks);
        lblBricks.setBounds(70, 40, 40, 20);

        lblWheat.setFont(new java.awt.Font("Dialog", 0, 12));
        lblWheat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWheat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Settlers/images/wheat2.jpg")));
        lblWheat.setText("00");
        lblWheat.setToolTipText("Wheat");
        add(lblWheat);
        lblWheat.setBounds(120, 40, 40, 20);

        lblSheep.setFont(new java.awt.Font("Dialog", 0, 12));
        lblSheep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSheep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Settlers/images/sheep2.jpg")));
        lblSheep.setText("00");
        lblSheep.setToolTipText("Sheep");
        add(lblSheep);
        lblSheep.setBounds(170, 40, 40, 20);

        lblOre.setFont(new java.awt.Font("Dialog", 0, 12));
        lblOre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Settlers/images/ore2.jpg")));
        lblOre.setText("00");
        lblOre.setToolTipText("Ore");
        add(lblOre);
        lblOre.setBounds(220, 40, 40, 20);

        btnTrade.setFont(new java.awt.Font("Dialog", 1, 10));
        btnTrade.setText("Trade...");
        add(btnTrade);
        btnTrade.setBounds(90, 70, 100, 20);

        lblDevelopment.setFont(new java.awt.Font("Lucida Bright", 1, 18));
        lblDevelopment.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDevelopment.setText("Development");
        add(lblDevelopment);
        lblDevelopment.setBounds(10, 100, 220, 22);

        lblKnights.setFont(new java.awt.Font("Dialog", 0, 12));
        lblKnights.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblKnights.setText("Army: 00");
        add(lblKnights);
        lblKnights.setBounds(10, 430, 70, 15);

        lblVPD0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Settlers/images/cathedral2.jpg")));
        lblVPD0.setToolTipText("Cathedral");
        lblVPD0.setEnabled(false);
        add(lblVPD0);
        lblVPD0.setBounds(10, 390, 20, 30);

        lblVPD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Settlers/images/tower2.jpg")));
        lblVPD1.setToolTipText("Tower");
        lblVPD1.setEnabled(false);
        add(lblVPD1);
        lblVPD1.setBounds(50, 390, 20, 30);

        lblVPD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Settlers/images/temple2.jpg")));
        lblVPD2.setToolTipText("Temple");
        lblVPD2.setEnabled(false);
        add(lblVPD2);
        lblVPD2.setBounds(90, 390, 20, 30);

        lblVPD3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Settlers/images/capital2.jpg")));
        lblVPD3.setToolTipText("Capital");
        lblVPD3.setEnabled(false);
        add(lblVPD3);
        lblVPD3.setBounds(130, 390, 20, 30);

        lblVPD4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Settlers/images/university2.jpg")));
        lblVPD4.setToolTipText("University");
        lblVPD4.setEnabled(false);
        add(lblVPD4);
        lblVPD4.setBounds(170, 390, 20, 30);

        lblVPD5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Settlers/images/courts2.jpg")));
        lblVPD5.setToolTipText("Courts");
        lblVPD5.setEnabled(false);
        add(lblVPD5);
        lblVPD5.setBounds(210, 390, 20, 30);

        lblVPD6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Settlers/images/library2.jpg")));
        lblVPD6.setToolTipText("Library");
        lblVPD6.setMaximumSize(new java.awt.Dimension(22, 32));
        lblVPD6.setMinimumSize(new java.awt.Dimension(22, 32));
        lblVPD6.setPreferredSize(new java.awt.Dimension(22, 32));
        lblVPD6.setEnabled(false);
        add(lblVPD6);
        lblVPD6.setBounds(250, 390, 22, 32);

        btnMonopoly.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Settlers/images/monopoly.jpg")));
        btnMonopoly.setText("00");
        btnMonopoly.setToolTipText("Monopoly");
        btnMonopoly.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMonopoly.setEnabled(false);
        add(btnMonopoly);
        btnMonopoly.setBounds(30, 130, 80, 30);

        btnKnight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Settlers/images/knight.jpg")));
        btnKnight.setText("00");
        btnKnight.setToolTipText("Army");
        btnKnight.setEnabled(false);
        add(btnKnight);
        btnKnight.setBounds(150, 130, 80, 30);

        lblCosts.setFont(new java.awt.Font("Lucida Bright", 1, 18));
        lblCosts.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCosts.setText("Costs");
        add(lblCosts);
        lblCosts.setBounds(10, 210, 260, 22);

        lblTitleVP.setFont(new java.awt.Font("Lucida Bright", 1, 18));
        lblTitleVP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleVP.setText("Victory Points");
        add(lblTitleVP);
        lblTitleVP.setBounds(10, 360, 260, 22);

        btnRoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Settlers/images/road.jpg")));
        btnRoad.setText("Road");
        btnRoad.setToolTipText("Road");
        btnRoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoadActionPerformed(evt);
            }
        });

        add(btnRoad);
        btnRoad.setBounds(10, 240, 110, 20);

        lblC0.setFont(new java.awt.Font("Dialog", 0, 12));
        lblC0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblC0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Settlers/images/wood2.jpg")));
        lblC0.setToolTipText("Wood");
        add(lblC0);
        lblC0.setBounds(130, 240, 20, 20);

        lblC1.setFont(new java.awt.Font("Dialog", 0, 12));
        lblC1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Settlers/images/bricks2.jpg")));
        lblC1.setToolTipText("Bricks");
        add(lblC1);
        lblC1.setBounds(160, 240, 20, 20);

        btnSettlement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Settlers/images/settlement.jpg")));
        btnSettlement.setText("Settlement");
        btnSettlement.setToolTipText("Settlement");
        btnSettlement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettlementActionPerformed(evt);
            }
        });

        add(btnSettlement);
        btnSettlement.setBounds(10, 270, 110, 20);

        lblC3.setFont(new java.awt.Font("Dialog", 0, 12));
        lblC3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblC3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Settlers/images/wood2.jpg")));
        lblC3.setToolTipText("Wood");
        add(lblC3);
        lblC3.setBounds(130, 270, 20, 20);

        lblC4.setFont(new java.awt.Font("Dialog", 0, 12));
        lblC4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblC4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Settlers/images/bricks2.jpg")));
        lblC4.setToolTipText("Bricks");
        add(lblC4);
        lblC4.setBounds(160, 270, 20, 20);

        lblC5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Settlers/images/wheat2.jpg")));
        add(lblC5);
        lblC5.setBounds(190, 270, 20, 20);

        lblC6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Settlers/images/sheep2.jpg")));
        add(lblC6);
        lblC6.setBounds(220, 270, 20, 20);

        btnCity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Settlers/images/city.jpg")));
        btnCity.setText("City");
        btnCity.setToolTipText("City");
        btnCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCiudadActionPerformed(evt);
            }
        });

        add(btnCity);
        btnCity.setBounds(10, 300, 110, 20);

        lblC7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Settlers/images/wheat2.jpg")));
        add(lblC7);
        lblC7.setBounds(130, 300, 20, 20);

        lblC8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Settlers/images/wheat2.jpg")));
        add(lblC8);
        lblC8.setBounds(160, 300, 20, 20);

        lblC9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Settlers/images/ore2.jpg")));
        add(lblC9);
        lblC9.setBounds(190, 300, 20, 20);

        lblC10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Settlers/images/ore2.jpg")));
        add(lblC10);
        lblC10.setBounds(220, 300, 20, 20);

        lblC11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Settlers/images/ore2.jpg")));
        add(lblC11);
        lblC11.setBounds(250, 300, 20, 20);

        btnCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Settlers/images/carta.jpg")));
        btnCard.setText("Card ");
        btnCard.setToolTipText("Card");
        btnCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCartaActionPerformed(evt);
            }
        });

        add(btnCard);
        btnCard.setBounds(10, 330, 110, 20);

        lblC12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Settlers/images/wheat2.jpg")));
        add(lblC12);
        lblC12.setBounds(130, 330, 20, 20);

        lblC13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Settlers/images/sheep2.jpg")));
        add(lblC13);
        lblC13.setBounds(160, 330, 20, 20);

        lblC14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Settlers/images/ore2.jpg")));
        add(lblC14);
        lblC14.setBounds(190, 330, 20, 20);

        lblVP.setText("Victory Points: 00");
        add(lblVP);
        lblVP.setBounds(130, 430, 140, 15);

        lblPlayers.setFont(new java.awt.Font("Lucida Bright", 1, 18));
        lblPlayers.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPlayers.setText("Players");
        add(lblPlayers);
        lblPlayers.setBounds(10, 460, 260, 22);

        lblJ1.setFont(new java.awt.Font("Dialog", 1, 10));
        lblJ1.setForeground(java.awt.Color.red);
        lblJ1.setText("P1 - Resources: 00 Development: 00 Army: 00 VP: 00");
        add(lblJ1);
        lblJ1.setBounds(10, 490, 270, 13);

        lblJ2.setFont(new java.awt.Font("Dialog", 1, 10));
        lblJ2.setForeground(java.awt.Color.blue);
        lblJ2.setText("P2 - Resources: 00 Development: 00 Army: 00 VP: 00");
        add(lblJ2);
        lblJ2.setBounds(10, 510, 270, 13);

        lblJ3.setFont(new java.awt.Font("Dialog", 1, 10));
        lblJ3.setForeground(java.awt.Color.green);
        lblJ3.setText("P3 - Resources: 00 Development: 00 Army: 00 VP: 00");
        add(lblJ3);
        lblJ3.setBounds(10, 530, 270, 13);

        lblJ4.setFont(new java.awt.Font("Dialog", 1, 10));
        lblJ4.setForeground(java.awt.Color.magenta);
        lblJ4.setText("P4 - Resources: 00 Development: 00 Army: 00 VP: 00");
        add(lblJ4);
        lblJ4.setBounds(10, 550, 270, 13);

        btnRoads.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Settlers/images/monopoly.jpg")));
        btnRoads.setText("00");
        btnRoads.setToolTipText("Road Building");
        btnRoads.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRoads.setEnabled(false);
        add(btnRoads);
        btnRoads.setBounds(150, 170, 80, 30);

        btnDiscovery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Settlers/images/monopoly.jpg")));
        btnDiscovery.setText("00");
        btnDiscovery.setToolTipText("Discovery");
        btnDiscovery.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDiscovery.setEnabled(false);
        add(btnDiscovery);
        btnDiscovery.setBounds(30, 170, 80, 30);

    }//GEN-END:initComponents

    private void btnCartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCartaActionPerformed
       parent.getController().buttonCard();
    }//GEN-LAST:event_btnCartaActionPerformed

    private void btnCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCiudadActionPerformed
        parent.getController().buttonCity();
    }//GEN-LAST:event_btnCiudadActionPerformed

    private void btnSettlementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettlementActionPerformed
        parent.getController().buttonSettlement();
    }//GEN-LAST:event_btnSettlementActionPerformed

    private void btnRoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoadActionPerformed
        parent.getController().buttonRoad();
    }//GEN-LAST:event_btnRoadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblC8;
    private javax.swing.JLabel lblVPD2;
    private javax.swing.JLabel lblC10;
    private javax.swing.JLabel lblVPD5;
    private javax.swing.JButton btnDiscovery;
    private javax.swing.JLabel lblC1;
    private javax.swing.JButton btnCity;
    private javax.swing.JLabel lblC9;
    private javax.swing.JLabel lblVPD3;
    private javax.swing.JLabel lblC4;
    private javax.swing.JLabel lblC11;
    private javax.swing.JLabel lblJ4;
    private javax.swing.JButton btnTrade;
    private javax.swing.JButton btnSettlement;
    private javax.swing.JLabel lblBricks;
    private javax.swing.JLabel lblC3;
    private javax.swing.JLabel lblC12;
    private javax.swing.JLabel lblWheat;
    private javax.swing.JLabel lblJ3;
    private javax.swing.JLabel lblPlayers;
    private javax.swing.JLabel lblVPD1;
    private javax.swing.JLabel lblVPD4;
    private javax.swing.JButton btnKnight;
    private javax.swing.JLabel lblKnights;
    private javax.swing.JLabel lblJ1;
    private javax.swing.JLabel lblDevelopment;
    private javax.swing.JLabel lblC5;
    private javax.swing.JButton btnRoad;
    private javax.swing.JLabel lblC0;
    private javax.swing.JLabel lblCosts;
    private javax.swing.JLabel lblVPD6;
    private javax.swing.JLabel lblC13;
    private javax.swing.JLabel lblTitleVP;
    private javax.swing.JLabel lblVP;
    private javax.swing.JLabel lblC6;
    private javax.swing.JLabel lblResources;
    private javax.swing.JLabel lblC14;
    private javax.swing.JButton btnMonopoly;
    private javax.swing.JButton btnCard;
    private javax.swing.JLabel lblWood;
    private javax.swing.JLabel lblC7;
    private javax.swing.JLabel lblJ2;
    private javax.swing.JButton btnRoads;
    private javax.swing.JLabel lblSheep;
    private javax.swing.JLabel lblVPD0;
    private javax.swing.JLabel lblOre;
    // End of variables declaration//GEN-END:variables
    
}
